name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: 18
    - uses: actions/setup-go@v5.0.0
      with:
        go-version: 1.20.1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: wget -O gf "https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH)" && chmod +x gf && ./gf install -y && rm ./gf
    - name: Build the Docker image
      run: ./release.sh
